apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-editor
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: registry.digitalocean.com/my-registry777/api-editor
        ports:
        - containerPort: 3005