apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-editor
  labels:
    app: website
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: registry.digitalocean.com/my-registry777/front-end-editor
        ports:
        - containerPort: 80